apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webapp
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - environment: dev
          - environment: prod
          - environment: stg
  template:
    metadata:
      name: '{{.environment}}-webapp'
    spec:
      project: default
      source:
        repoURL: https://github.com/jpedrosa94/p2p-devops-test.git
        targetRevision: HEAD
        path: charts/webapp
        helm:
          valueFiles:
            - "values-{{.environment}}.yaml"
      destination:
        # Default base cluster
        name: in-cluster
        namespace: "{{.environment}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - cluster: engineering-dev
            url: https://1.2.3.4
          - cluster: engineering-prod
            url: https://2.4.6.8
          - cluster: finance-preprod
            url: https://9.8.7.6
  template:
    metadata:
      name: '{{.cluster}}-guestbook'
    spec:
      project: my-project
      source:
        repoURL: https://github.com/infra-team/cluster-deployments.git
        targetRevision: HEAD
        path: guestbook/{{.cluster}}
      destination:
        server: '{{.url}}'
        namespace: guestbook