apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-boostrap
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/cluster-bootstrap
    repoURL: https://github.com/jpedrosa94/p2p-devops-test.git
    targetRevision: {{ .Values.ref }}
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
spec:
  destination:
    namespace: webapp
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/webapp
    repoURL: https://github.com/jpedrosa94/p2p-devops-test.git
    targetRevision: {{ .Values.ref }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true