# Every time a PR is opened/synchronized or re-opened to develop the workflow will be triggered
name: "run tests"

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ develop ]

concurrency:
  group: ci-dev-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dev-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

#      - name: Set up Go
#        uses: actions/setup-go@v4
#        with:
#          go-version: '1.22'
#
#      - name: Run Unit Tests
#        run: go test main_test.go

      - name: Set variables
        run: |
          echo "FILE_PATH=charts/webapp/values-dev.yaml" >> $GITHUB_ENV
          echo "IMAGE_REGISTRY=juliopedrosa/webapp" >> $GITHUB_ENV
          echo "IMAGE_TAG=dev-2" >> $GITHUB_ENV
          
      - name: Update image tag in YAML file
        run: |
          sed -i 's/^  tag: .*/  tag: '"${{ env.IMAGE_TAG }}"'/' ${{ env.FILE_PATH }}
          cat charts/webapp/values-dev.yaml

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update image tag to ${{ env.IMAGE_TAG }}"
          branch: master
          file_pattern: ${{ env.FILE_PATH }}
